<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Windows-only target. Uno lets you add net9.0-ios, net9.0-android, etc. later -->
    <TargetFramework>net9.0-windows10.0.19041</TargetFramework>

	<WindowsPackageType>None</WindowsPackageType>

    <OutputType>WinExe</OutputType>
    <RootNamespace>TeamsVoiceWizard</RootNamespace>
    <AssemblyName>TeamsVoiceWizard</AssemblyName>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>


    <DefaultLanguage>en-GB</DefaultLanguage>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260317003" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.1.2" />
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.4.6" />
    <PackageReference Include="System.Management.Automation" Version="7.4.6" />
  </ItemGroup>

  <ItemGroup>
    <!-- Copy the core PowerShell module to the output directory -->
    <Content Include="core\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>